# Search Project Config

## Disable APM and Uptime, enable Enterprise Search
xpack.apm.enabled: false
xpack.uptime.enabled: false
enterpriseSearch.enabled: true

## Configure Enterprise Search plugin to run without ent-search node
enterpriseSearch.canDeployEntSearch: false
enterpriseSearch.hasConnectors: false
enterpriseSearch.hasDefaultIngestPipeline: false
enterpriseSearch.hasNativeConnectors: false
enterpriseSearch.hasWebCrawler: false

## Enable the Serverless Search plugin
xpack.serverless.search.enabled: true

## Set the home route
uiSettings.overrides.defaultRoute: /app/elasticsearch

## Set the dev project switcher current type
xpack.serverless.plugin.developer.projectSwitcher.currentType: 'search'
